---
- name: 'assert | Ensure _fd_packages is defined properly'
  ansible.builtin.assert:
    that:
      # ensure all files that don't have a source defined, have content defined
      - >-
        _fd_files |
        rejectattr('src', 'defined') |
        selectattr('content', 'undefined') |
        length == 0

      # ensure all files that don't have content defined, have a source defined
      - >-
        _fd_files |
        rejectattr('content', 'defined') |
        selectattr('src', 'undefined') |
        length == 0

    success_msg: 'Files are defined correctly'
    fail_msg: 'One or more failed failed to validated correctly'
    quiet: '{{ _fd_quiet_assert }}'
...
