---
- name: 'Verify'
  hosts: 'molecule'
  gather_facts: false

  tasks:
    - name: 'Gather information about the transfered file'
      ansible.builtin.stat:
        path: '/tmp/test.file'
      become: true
      register: '__t_test_file'

    - name: 'Ensure test.file has the specified permissions set'
      ansible.builtin.assert:
        that:
          # exists
          - '__t_test_file.stat.exists is defined'
          - '__t_test_file.stat.exists'

          # owner
          - '__t_test_file.stat.pw_name is defined'
          - "__t_test_file.stat.pw_name == 'root'"

          # group
          - '__t_test_file.stat.gr_name is defined'
          - "__t_test_file.stat.gr_name == 'root'"

          # mode
          - '__t_test_file.stat.mode is defined'
          - "__t_test_file.stat.mode == '0700'"

    - name: 'Gather information about the created file'
      ansible.builtin.stat:
        path: '/tmp/test.content'
      become: true
      register: '__t_test_content'

    - name: 'Ensure test.file has the specified permissions set'
      ansible.builtin.assert:
        that:
          # exists
          - '__t_test_content.stat.exists is defined'
          - '__t_test_content.stat.exists'

          # owner
          - '__t_test_content.stat.pw_name is defined'
          - "__t_test_content.stat.pw_name == 'root'"

          # group
          - '__t_test_content.stat.gr_name is defined'
          - "__t_test_content.stat.gr_name == 'root'"

          # mode
          - '__t_test_content.stat.mode is defined'
          - "__t_test_content.stat.mode == '0600'"
...
