---
name: 'Publish latest release to Ansible Galaxy'

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'

      - name: 'galaxy'
        uses: 'robertdebock/galaxy-action@1.2.0'
        with:
          galaxy_api_key: '${{ secrets.galaxy_api_key }}'
          git_branch: 'main'

      - name: 'Create a new release on GitHub'
        uses: 'softprops/action-gh-release@v2'
        with:
          draft: false
          prerelease: false
          token: '${{ github.token }}'
          discussion_category_name: 'Release'
          generate_release_notes: true
          make_latest: true
...
