---
name: 'Contributors'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  contributors:
    name: 'Add contributors'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6' # v2.8.1
        with:
          egress-policy: 'block'
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443

      - name: 'Checkout the repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7
        with:
          fetch-depth: 0

      - name: 'Add contributors'
        uses: 'akhilmhdh/contributors-readme-action@1ff4c56187458b34cd602aee93e897344ce34bfc' # v2.3.10
        with:
          auto_detect_branch_protection: false
          collaborators: 'all'
          committer_email: 'contributors-action@scheib.me'
          committer_username: 'Contributors Action'
          readme_path: 'docs/CONTRIBUTORS.md'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
...
