---
name: 'molecule'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: 'choice'
        default: 'enabled'
        options:
          - 'enabled'
          - 'disabled'
          - 'reset'

permissions:
  contents: 'read'

# Adding these as env variables makes it easy to re-use them in different steps and in bash.
env:
  cache_archive: 'molecule_cache.tar.gz'
  # This is the dir renovate provides
  # If we set our own directory via cacheDir, we can run into permissions issues.
  # It is also possible to cache a higher level of the directory, but it has minimal benefit. While renovate execution
  # time gets faster, it also takes longer to upload the cache as it grows bigger.
  cache_dir: '/tmp/.cache/molecule'
  # This can be manually changed to bust the cache if neccessary.
  cache_key: 'molecule-cache'

jobs:
  molecule:
    permissions:
      contents: 'write'
    runs-on: 'ubuntu-latest'
    container: 'registry.access.redhat.com/ubi8/podman'
    strategy:
      matrix:
        ansible_version:
          - '2.16'
        #  - '2.14'
        #  - '2.15'
        #  - '2.17'
        python_version:
          - '3.12'
        #  - '3.6'
        #  - '3.7'
        #  - '3.8'
        #  - '3.9'
        #  - '3.10'
        #  - '3.11'
        # exclude:
        #  - ansible_version: '2.17'
        #    python_version: '3.6'

    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6' # v2.8.1
        with:
          egress-policy: 'audit'

      - name: 'Install NodeJS'
        run: 'dnf install nodejs -y'

      - name: 'Checkout repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7

      - name: 'Download cache of the previous workflow run'
        uses: 'dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11' # v6
        if: "github.event.inputs.repoCache != 'disabled'"
        continue-on-error: true
        with:
          name: '${{ env.cache_key }}'
          path: 'cache-download'

      - name: 'Extract molecule cache to improve performance'
        run: |
          set -x
          # Skip if no cache is set, such as the first time it runs.
          if [ ! -d cache-download ] ; then
            echo "No cache found."
            exit 0
          fi

          # Make sure the directory exists, and extract it there. Note that it's nested in the download directory.
          mkdir -p "${cache_dir}"
          tar -xzf "cache-download/${cache_archive}" -C "${cache_dir}"

      - name: 'Install Python'
        run: |
          dnf install -y python${{ matrix.python_version }} python${{ matrix.python_version }}-pip

      - name: 'Install Python packages'
        run: |
          pip${{ matrix.python_version }} install ansible-core==${{ matrix.ansible_version }}.*
          # renovate: datasource=pypi
          pip${{ matrix.python_version }} install molecule==24.6.0
          mkdir -pv "${cache_dir}"

      - name: 'Run molecule'
        run: |
          molecule test

      - name: 'Compress molecule cache to improve performance'
        run: |
          # The -C is important, as otherwise we end up extracting the files with
          # their full path, ultimately leading to a nested directory situation.
          tar -czf "${cache_archive}" -C "${cache_dir}" .

      - name: 'Upload compressed cache'
        uses: 'actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808' # v4.3.3
        if: "github.event.inputs.repoCache != 'disabled'"
        with:
          name: '${{ env.cache_key }}'
          path: '${{ env.cache_archive }}'
          # Since this is updated and restored on every run, we don't need to keep it
          # for long. Just make sure this value is large enough that multiple renovate
          # runs can happen before older cache archives are deleted.
          retention-days: 1
...
