---
name: 'pre-commit'
on:  # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  pre-commit:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6' # v2.8.1
        with:
          egress-policy: 'audit'

      - name: 'Install aspell'
        run: 'sudo apt-get update && sudo apt-get install -y aspell aspell-en'

      - name: 'Checkout repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7

      - name: 'Install Python'
        uses: 'actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d' # v5.1.0
        with:
          python-version: '3.11'

      - name: 'Run pre-commit'
        uses: 'pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd' # v3.0.1
...
