---
name: 'pyspelling'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  pyspelling:
    name: 'pyspelling'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6' # v2.8.1
        with:
          egress-policy: 'block'
          disable-sudo: true
          allowed-endpoints: >
            github.com:443

      - name: 'Checkout the repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7

      - name: 'Run pyspelling'
        uses: 'rojopolis/spellcheck-github-actions@5922d6e80234a4b230c51f2af3b9e29f29263eb7' # 0.39.0
        with:
          config_path: '.github/spellcheck/spellcheck.yml'
...
