---
name: 'Publish to Ansible Galaxy'
on:  # yamllint disable-line rule:truthy
#  push:
#    branches:
#      - 'main'
  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  release:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6' # v2.8.1
        with:
          egress-policy: 'audit'

      - name: 'Checkout the repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7
        with:
          fetch-depth: 0

      - name: 'Create a semantic release'
        uses: 'cycjimmy/semantic-release-action@61680d0e9b02ff86f5648ade99e01be17f0260a4' # v4.0.0
        env:
          GH_TOKEN: '${{ secrets.RELEASE_TOKEN }}'
        with:
          extra_plugins: |
            semantic-release-github-pullrequest@v1.3.0

      - name: 'Publish to Ansible Galaxy'
        uses: 'robertdebock/galaxy-action@7d89099e09f4385ec4b53eb58c0d120f1ad806dd' # 1.2.1
        with:
          galaxy_api_key: '${{ secrets.galaxy_api_key }}'
          git_branch: 'main'
 #
 #      - name: 'Create a new release on GitHub'
#        uses: 'softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87' # v2.0.5
#        if: "contains(needs.check-current-branch.outputs.branch, 'main')"
#        with:
#          draft: false
#          prerelease: false
#          token: '${{ secrets.release_token }}'
#          discussion_category_name: 'Announcements'
#          generate_release_notes: true
#          make_latest: true
...
