---
name: 'wrapper workflow to call molecule certified EEs workflow'
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - 'labeled'

    paths:
      - '.github/workflows/molecule_certified_ees.yml'
      - '.github/workflows/wrapper_call_molecule_certified_ees_workflow.yml'
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'library/**'
      - 'lookup_plugins/**'
      - 'meta/**'
      - 'module_utils/**'
      - 'tasks/**'
      - 'templates/**'
      - 'vars/**'

  push:
    branches:
      - 'main'

    paths:
      - '.github/workflows/molecule_certified_ees.yml'
      - '.github/workflows/wrapper_call_molecule_certified_ees_workflow.yml'
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'library/**'
      - 'lookup_plugins/**'
      - 'meta/**'
      - 'module_utils/**'
      - 'tasks/**'
      - 'templates/**'
      - 'vars/**'

  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: 'choice'
        default: 'enabled'
        options:
          - 'enabled'
          - 'disabled'
          - 'reset'

permissions:
  contents: 'read'

jobs:
  call-workflow:
    permissions:
      contents: 'write'
    name: 'Include molecule workflow'
    if: >-
      contains(github.event.pull_request.labels.*.name, 'run') ||
      github.ref == 'refs/heads/main'
    uses: './.github/workflows/molecule_certified_ees.yml'
    with:
      repoCache: "${{ github.event.inputs.repoCache }}"
    secrets:
      CRC_USERNAME: '${{ secrets.CRC_USERNAME }}'
      CRC_PASSWORD: '${{ secrets.CRC_PASSWORD }}'
      token: '${{ secrets.GITHUB_TOKEN }}'
...
